### ISSUE TITLE
Make it possible for user to change rows and columns

### ISSUE THREAD

**Issue by juliasophieg** [juliasophieg/n-puzzle-game#1]
Right now, you can only do it by modifying the code in the App.jsx file, located at the top of the App function:

<img width="659" alt="Screenshot 2024-09-09 at 20 50 58" src="https://github.com/user-attachments/assets/46d467dc-5a9e-420f-8935-14b698dd8e6d">

**Comment by NicholasChristopherBlake** [comment]
Hello! Just added such functionality
https://github.com/juliasophieg/n-puzzle-game/pull/2

**Comment by juliasophieg** [comment]
@NicholasChristopherBlake Nicely done, thank you! ✨
